### ISSUE TITLE
Diagnostics

### ISSUE THREAD

**Issue by Lukalukito** [DanielGavin/ols#328]
diagnostics are ... terrible. code runs but ols shows some errors (on neovim and vscode). i am just learning but so i really depend on lsp autocompletions and diagnostics.
![2024-03-27-225732_hyprshot](https://github.com/DanielGavin/ols/assets/91207566/1a0964a2-df0d-4e0a-8733-75c0021290da)
![2024-03-27-225757_hyprshot](https://github.com/DanielGavin/ols/assets/91207566/9d2614f4-5e57-44f2-97a6-9bd6bb92dc51)
I am pretty sure that is a bug.

am on arch linux

**Comment by DanielGavin** [comment]
Next time write the code snippets. It's easier to test the code.

Right now there is issues with the latest Odin version causing issues with Linux and Darwin.

You could try Odin commit: ed5fd15f6e567c41e1b9cb2c272461f685b9efd2

Until this is fixed, I won't be looking at issues with Linux and Darwin. Many of tests for ols is failing now because of it.

**Comment by Lukalukito** [comment]
sorry for being late. it works, thanks
