### ISSUE TITLE
DOC on hover not working for core lib

### ISSUE THREAD

**Issue by jpx40** [DanielGavin/ols#499]
Hey, 
i use neovim i noticed that the doc on hover for core libs doesn't work. For other imports it works fine.

**Comment by DanielGavin** [comment]
Not sure what you mean. Are you talking about hovering on symbols in the actual files in `core`? Some of those can't be hovered since the parser won't run in those files. Can't fix that on my end.

**Comment by jpx40** [comment]
> Not sure what you mean. Are you talking about hovering on symbols in the actual files in `core`? Some of those can't be hovered since the parser won't run in those files. Can't fix that on my end.
> 
> You need to give an example.

so, the doc files are the only files u are not parsing? this would explain why they won't show the docs.

**Comment by jpx40** [comment]
> Not sure what you mean. Are you talking about hovering on symbols in the actual files in `core`? Some of those can't be hovered since the parser won't run in those files. Can't fix that on my end.
> 
> You need to give an example.

the parsed doc comments wouldn't show up

**Comment by jpx40** [comment]
could u bundle the std lib with your binary and parse them then like the rest?

**Comment by jpx40** [comment]
u could use this function 
```
foo := #load("path/to/file")
bar := #load("path/to/file", string)
fmt.println(bar)

// If a file's size is not a multiple of the `size_of(type)`, then any remainder is ignored.
baz := #load("path/to/file", []f32)
```
http://odin-lang.org/docs/overview/#loadstring-path-or-loadstring-path-type

**Comment by DanielGavin** [comment]
Please give an example. I don't understand what you mean with `parsed doc comments wouldn't show up`.

You might as well say it doesn't work as an issue, it's just as helpful.

Doc comments work:
![billede](https://github.com/user-attachments/assets/2cf43aa2-0afe-4d02-9c3c-202aa75cd61a)


A doc comment is a comment that is right over the function. That clearly works. If there is a bug in a specific file/package then please refer to that.

As I mentioned there are issue with being inside the `core` in certain files where the parser is disabled, and that can't be fixed until it is fixed in `core:odin/parser`.

**Comment by jpx40** [comment]
i can see any docs for functions of core when i use the over feature in neovim

**Comment by jpx40** [comment]
fixed it with setting ODIN_ROOT

**Comment by DanielGavin** [comment]
Surprised you had any completion, let any doc comments, without it being to find odin root. But glad that it now works for you.

**Comment by jpx40** [comment]
> Surprised you had any completion then without it being to find odin root. But glad that it now works for you.

i disabled completion i just needed the doc feature xd
